CREATE TABLE course (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    coursecode VARCHAR(255) DEFAULT NULL,
    coursename VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (coursecode)
);


CREATE TABLE note (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    filename VARCHAR(255) DEFAULT NULL,
    content_type VARCHAR(255) DEFAULT NULL,
    content BLOB DEFAULT NULL,
    coursecode VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (coursecode) REFERENCES course(coursecode)
);