CREATE TABLE polling (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question VARCHAR(255) DEFAULT NULL,
option1 VARCHAR(255) DEFAULT NULL,
option2 VARCHAR(255) DEFAULT NULL,
option3 VARCHAR(255) DEFAULT NULL,
option4 VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pollingRecord (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    username VARCHAR(255) DEFAULT NULL,
    question VARCHAR(255) DEFAULT NULL,
    choice VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pollingResult (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question VARCHAR(255) DEFAULT NULL,
    totalchoiceA INT DEFAULT 0,
    totalchoiceB INT DEFAULT 0,
    totalchoiceC INT DEFAULT 0,
    totalchoiceD INT DEFAULT 0,
    PRIMARY KEY (id)
);




