CREATE TABLE student (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    username VARCHAR(255) DEFAULT NULL,
    password VARCHAR(255) DEFAULT NULL,
    fullname VARCHAR(255) DEFAULT NULL,
    phonenumber VARCHAR(255) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    userrole VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (username)
);
