CREATE TABLE voteduser (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question VARCHAR(255) DEFAULT NULL,
    username VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);
