CREATE TABLE pollingcomment (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question VARCHAR(255) DEFAULT NULL,
    username VARCHAR(255) DEFAULT NULL,
    comment VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE coursecomment (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    course VARCHAR(255) DEFAULT NULL,
    username VARCHAR(255) DEFAULT NULL,
    comment VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

